# Generated by Django 5.2.7 on 2026-04-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0009_customuser_is_online_customuser_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_from',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_to',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('follower', 'following')},
        ),
    ]
