# Generated by Django 5.2.7 on 2026-03-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp', 'pk']},
        ),
    ]
