# Generated by Django 5.2.7 on 2026-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_chat_remove_notification_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'liked your post'), ('COMMENT', 'commented on your post'), ('MESSAGE', 'sent you a message'), ('FOLLOW', 'started following you')], default='LIKE', max_length=20),
        ),
    ]
