name: Awake Server

on:
  schedule:
    # Розрахунок для UTC. Якщо в Україні 8:00-20:00, 
    # то для UTC це 5:00-17:00 (влітку)
    - cron: '*/10 6-18 * * *'
  workflow_dispatch: # щоб ти міг запустити вручну для тесту

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP HEAD request
        run: curl -I https://kasagram.onrender.com/api/ping/?format=json
